# Optional - The name of the workflow as it will appear in the "Actions" tab of the GitHub repository. If this field is omitted, the name of the workflow file will be used instead.
name: Test

run-name: ${{ github.actor }} is learning GitHub Actions

on: [push]

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: Xotabu4/selenoid-github-action@v2
      - run: chmod +x ./gradlew
      - run: ./gradlew clean test -Dselenide.remote=http://localhost:4444/wd/hub

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure-results: build/allure-results
          gh-pages: gh-pages
          allure-report: allure-report
          allure-history: allure-history

      - uses: peaceiris/actions-gh-pages@v2
        if: always()
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish_branch: gh-pages
          publish_dir: allure-history
